"""comments table modified.

Revision ID: 156124c92c9f
Revises: 2ca9cbc155a1
Create Date: 2018-04-20 08:57:07.715482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156124c92c9f'
down_revision = '2ca9cbc155a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=1000), nullable=True))
    op.add_column('comments', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'comments', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_column('comments', 'email')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
